FROM registry.cn-shenzhen.aliyuncs.com/elastic-group/kibana:6.8.23
ADD zh-CN.json /usr/share/kibana/src/legacy/core_plugins/kibana/translations/zh-CN.json
COPY index.css /usr/share/kibana/built_assets/css/plugins/kibana/index.css

